version: "3.9"
services:
  tg-bot:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: tg_bot
    container_name: tg_bot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../:/app/
    env_file:
      - ../.env
